version: '3.9'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stm
    volumes:
      - stm-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ./backend
    depends_on:
      - db
    env_file:
      - backend/.env
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm run dev"

  web:
    build:
      context: ./frontend
    depends_on:
      - api
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3333/api
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

volumes:
  stm-data:
